// <auto-generated />
using System;
using HonestLabel.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HonestLabel.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260103062328_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("HonestLabel.API.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 446, DateTimeKind.Utc).AddTicks(5448),
                            Email = "admin@honestlabel.in",
                            IsActive = true,
                            Name = "Admin",
                            PasswordHash = "$2a$11$K5VxmhKPcQVf8Y9q8qzqQeJ8zU0a3wFzNwKz5YhF.kpZzF5DQwXWa",
                            Role = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("HonestLabel.API.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Excerpt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("HonestLabel.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 445, DateTimeKind.Utc).AddTicks(6436),
                            Description = "Weatherproof polyester labels, cold-storage barcode labels, safety zone labels",
                            Icon = "lucide:shield",
                            IsActive = true,
                            Name = "Specialty Labels",
                            Slug = "specialty-labels"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 445, DateTimeKind.Utc).AddTicks(7226),
                            Description = "Tamper-resistant holographic labels, warranty labels, void tamper-proof labels",
                            Icon = "lucide:lock",
                            IsActive = true,
                            Name = "Security & Compliance",
                            Slug = "security-compliance"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 445, DateTimeKind.Utc).AddTicks(7229),
                            Description = "Promotional labels, jewelry tags, custom branding labels",
                            Icon = "lucide:tag",
                            IsActive = true,
                            Name = "Retail & Branding",
                            Slug = "retail-branding"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 445, DateTimeKind.Utc).AddTicks(7231),
                            Description = "Specialized labels for rigorous industrial demands",
                            Icon = "lucide:factory",
                            IsActive = true,
                            Name = "Industrial Labels",
                            Slug = "industrial-labels"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 445, DateTimeKind.Utc).AddTicks(7232),
                            Description = "Compostable food-safe labels, recyclable packaging labels",
                            Icon = "lucide:leaf",
                            IsActive = true,
                            Name = "Eco-Friendly Labels",
                            Slug = "eco-friendly"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 445, DateTimeKind.Utc).AddTicks(7233),
                            Description = "Custom pre-printed barcode labels, weatherproof variants",
                            Icon = "lucide:barcode",
                            IsActive = true,
                            Name = "Barcode Labels",
                            Slug = "barcode-labels"
                        });
                });

            modelBuilder.Entity("HonestLabel.API.Models.Inquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inquiries");
                });

            modelBuilder.Entity("HonestLabel.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Features")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 446, DateTimeKind.Utc).AddTicks(2445),
                            DisplayOrder = 0,
                            ImageUrl = "https://honestlabel.in/wp-content/uploads/2024/03/Barcode-Labels-for-Lab-Vials-3.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Lab Vial Barcodes",
                            ShortDescription = "High-precision barcodes designed for small circumference vials. Cryogenic and moisture resistant.",
                            Slug = "lab-vial-barcodes"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 446, DateTimeKind.Utc).AddTicks(3676),
                            DisplayOrder = 0,
                            ImageUrl = "https://honestlabel.in/wp-content/uploads/2024/03/Retail-Garment-Tags-1.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Retail Garment Tags",
                            ShortDescription = "Premium hang tags and adhesive labels for clothing with high-quality print finish.",
                            Slug = "retail-garment-tags"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 446, DateTimeKind.Utc).AddTicks(3677),
                            DisplayOrder = 0,
                            ImageUrl = "https://honestlabel.in/wp-content/uploads/2025/02/Floor-Marking-Stickers-1.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Floor Marking Stickers",
                            ShortDescription = "Heavy-duty, abrasion-resistant floor graphics for warehouse safety and directional signage.",
                            Slug = "floor-marking-stickers"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 446, DateTimeKind.Utc).AddTicks(3679),
                            DisplayOrder = 0,
                            ImageUrl = "https://honestlabel.in/wp-content/uploads/2024/03/Void-Tamper-Proof-Labels-1.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Void Tamper Proof Labels",
                            ShortDescription = "Leaves a 'VOID' residue when removed. Essential for warranty seals and asset protection.",
                            Slug = "void-tamper-proof"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 446, DateTimeKind.Utc).AddTicks(3680),
                            DisplayOrder = 0,
                            ImageUrl = "https://honestlabel.in/wp-content/uploads/2025/02/Active-RFID-Labels-for-Tracking-3.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Active RFID Labels",
                            ShortDescription = "Smart labels embedded with RFID chips for real-time inventory tracking and logistics.",
                            Slug = "active-rfid-labels"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 446, DateTimeKind.Utc).AddTicks(3681),
                            DisplayOrder = 0,
                            ImageUrl = "https://honestlabel.in/wp-content/uploads/2025/02/Bath-and-Beauty-Product-Labels-3.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Bath & Beauty Labels",
                            ShortDescription = "Waterproof and oil-resistant finishes tailored for shampoos, soaps, and lotions.",
                            Slug = "bath-beauty-labels"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 446, DateTimeKind.Utc).AddTicks(3682),
                            DisplayOrder = 0,
                            ImageUrl = "https://honestlabel.in/wp-content/uploads/2025/02/Biodegradable-Labels-for-Disposable-Items-3.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Biodegradable Labels",
                            ShortDescription = "Sustainable labeling solutions for disposable items, fully compostable materials.",
                            Slug = "biodegradable-labels"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 446, DateTimeKind.Utc).AddTicks(3683),
                            DisplayOrder = 0,
                            ImageUrl = "https://honestlabel.in/wp-content/uploads/2024/03/Tamper-Proof-Neck-Labels-3.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Bottle Neck Labels",
                            ShortDescription = "Specialized seals for bottles and jars to ensure product integrity and freshness.",
                            Slug = "bottle-neck-labels"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 446, DateTimeKind.Utc).AddTicks(3684),
                            DisplayOrder = 0,
                            ImageUrl = "https://honestlabel.in/wp-content/uploads/2024/03/Sterilized-Equipment-Labels-1.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Sterilized Equipment Labels",
                            ShortDescription = "Autoclave-safe labels that withstand high heat and sterilization processes.",
                            Slug = "sterilized-equipment-labels"
                        });
                });

            modelBuilder.Entity("HonestLabel.API.Models.SiteSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SiteSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Company name",
                            Key = "company_name",
                            UpdatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 446, DateTimeKind.Utc).AddTicks(4470),
                            Value = "Honest Label"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Company tagline",
                            Key = "company_tagline",
                            UpdatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 446, DateTimeKind.Utc).AddTicks(4989),
                            Value = "Labeling Solutions That Work"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Contact phone",
                            Key = "phone",
                            UpdatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 446, DateTimeKind.Utc).AddTicks(4990),
                            Value = "+91 95123 70018"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Contact email",
                            Key = "email",
                            UpdatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 446, DateTimeKind.Utc).AddTicks(4991),
                            Value = "hello@honestit.in"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Office address",
                            Key = "address",
                            UpdatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 446, DateTimeKind.Utc).AddTicks(4992),
                            Value = "170/171, HonestIT - Corporate House, Besides Sanskruti Building, Near Old High-Court, Ashram Rd, Ahmedabad, Gujarat 380009"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Business hours",
                            Key = "business_hours",
                            UpdatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 446, DateTimeKind.Utc).AddTicks(4993),
                            Value = "Monday - Saturday: 9:30 AM - 6:30 PM"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Facebook page URL",
                            Key = "facebook_url",
                            UpdatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 446, DateTimeKind.Utc).AddTicks(4993),
                            Value = ""
                        },
                        new
                        {
                            Id = 8,
                            Description = "LinkedIn page URL",
                            Key = "linkedin_url",
                            UpdatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 446, DateTimeKind.Utc).AddTicks(4994),
                            Value = ""
                        },
                        new
                        {
                            Id = 9,
                            Description = "Instagram page URL",
                            Key = "instagram_url",
                            UpdatedAt = new DateTime(2026, 1, 3, 6, 23, 28, 446, DateTimeKind.Utc).AddTicks(4995),
                            Value = ""
                        });
                });

            modelBuilder.Entity("HonestLabel.API.Models.Product", b =>
                {
                    b.HasOne("HonestLabel.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HonestLabel.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
